// This file is auto-generated by @hey-api/openapi-ts

import { createRequestFx, createQuery, createMutation } from 'effector-refetch';
import { type Options, findPetsByStatus, getPetById, addPet } from './sdk.gen';
import type { FindPetsByStatusData, GetPetByIdData, AddPetData } from './types.gen';


/**
 * Query for `GET /pet/findByStatus`
 * Finds pets by status
 */
export const findPetsByStatusQuery = createQuery({
  name: 'findPetsByStatus',
  effect: createRequestFx((params: Options<FindPetsByStatusData>, { signal }: { signal: AbortSignal }) =>
    findPetsByStatus({ ...params, signal, throwOnError: true }).then((r) => r.data)),
});


/**
 * Query for `GET /pet/{petId}`
 * Find pet by ID
 */
export const getPetByIdQuery = createQuery({
  name: 'getPetById',
  effect: createRequestFx((params: Options<GetPetByIdData>, { signal }: { signal: AbortSignal }) =>
    getPetById({ ...params, signal, throwOnError: true }).then((r) => r.data)),
});


/**
 * Mutation for `POST /pet`
 * Add a new pet to the store
 */
export const addPetMutation = createMutation({
  name: 'addPet',
  effect: createRequestFx((params: Options<AddPetData>, { signal }: { signal: AbortSignal }) =>
    addPet({ ...params, signal, throwOnError: true }).then((r) => r.data)),
});