// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { FindPetsByStatusData, FindPetsByStatusResponses, GetPetByIdData, GetPetByIdResponses, AddPetData, AddPetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Finds pets by status
 */
export const findPetsByStatus = <ThrowOnError extends boolean = false>(options?: Options<FindPetsByStatusData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<FindPetsByStatusResponses, unknown, ThrowOnError>({
        url: '/pet/findByStatus',
        ...options
    });
};

/**
 * Find pet by ID
 */
export const getPetById = <ThrowOnError extends boolean = false>(options: Options<GetPetByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPetByIdResponses, unknown, ThrowOnError>({
        url: '/pet/{petId}',
        ...options
    });
};

/**
 * Add a new pet to the store
 */
export const addPet = <ThrowOnError extends boolean = false>(options: Options<AddPetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddPetResponses, unknown, ThrowOnError>({
        url: '/pet',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};