// This file is auto-generated by @hey-api/openapi-ts

export type Pet = {
    id?: number;
    name: string;
    photoUrls: Array<string>;
    status?: 'available' | 'pending' | 'sold';
};

export type FindPetsByStatusData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'available' | 'pending' | 'sold';
    };
    url: '/pet/findByStatus';
};

export type FindPetsByStatusResponses = {
    /**
     * successful operation
     */
    200: Array<Pet>;
};

export type FindPetsByStatusResponse = FindPetsByStatusResponses[keyof FindPetsByStatusResponses];

export type GetPetByIdData = {
    body?: never;
    path: {
        petId: number;
    };
    query?: never;
    url: '/pet/{petId}';
};

export type GetPetByIdResponses = {
    /**
     * successful operation
     */
    200: Pet;
};

export type GetPetByIdResponse = GetPetByIdResponses[keyof GetPetByIdResponses];

export type AddPetData = {
    body: Pet;
    path?: never;
    query?: never;
    url: '/pet';
};

export type AddPetResponses = {
    /**
     * successful operation
     */
    200: Pet;
};

export type AddPetResponse = AddPetResponses[keyof AddPetResponses];

export type ClientOptions = {
    baseUrl: 'https://petstore3.swagger.io/api/v3' | (string & {});
};