/**
 * Demo: queries generated from an OpenAPI spec by `effector-refetch/openapi`.
 *
 * `src/api/` is generated by @hey-api/openapi-ts from ./petstore.json
 * (see ./openapi-ts.config.ts) and talks to the live petstore3 sandbox.
 *
 * Regenerate: cd examples/openapi-codegen && npx openapi-ts   (build dist first: pnpm build)
 * Run:        npx tsx examples/openapi-codegen/main.ts
 */
import { allSettled, fork } from 'effector';
import { retry } from 'effector-refetch';
import { addPetMutation, findPetsByStatusQuery, getPetByIdQuery } from './src/api/refetch.gen';

// Generated definitions are plain queries — operators compose as usual.
retry(getPetByIdQuery, { times: 2 });

async function main() {
  const scope = fork();

  // 1. Typed query: params shape (`query.status`) comes from the spec.
  await allSettled(findPetsByStatusQuery.start, {
    scope,
    params: { query: { status: 'available' } },
  });
  // $state is a discriminated union: `done` narrows data to non-null.
  const found = scope.getState(findPetsByStatusQuery.$state);
  if (found.status === 'done') {
    console.log(`available pets: ${found.data.length}`);
  } else {
    console.error('findPetsByStatus failed:', found.error);
  }

  // 2. Typed mutation: the body is checked against the spec's Pet schema.
  await allSettled(addPetMutation.start, {
    scope,
    params: { body: { name: 'Bella', photoUrls: [], status: 'available' } },
  });
  const created = scope.getState(addPetMutation.$data);
  console.log('created pet:', created?.id, created?.name);

  // 3. Path params are typed too; `$data` narrows to the spec's Pet type.
  if (created?.id != null) {
    await allSettled(getPetByIdQuery.start, { scope, params: { path: { petId: created.id } } });
    console.log('fetched back:', scope.getState(getPetByIdQuery.$data)?.name);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
